from groq import Groq

company_name = "INflow Federal"
description = """
        "Description": "Outlier helps the world\u2019s most innovative companies improve their AI models by providing human feedback. Are you an experienced Machine Learning expert who would like to lend your expertise to train AI models?\n\nAbout the opportunity:\n\nOutlier is looking for talented machine learning experts to help train generative artificial intelligence models\nThis freelance opportunity is remote and hours are flexible, so you can work whenever is best for you\nYou may contribute your expertise by\u2026\n\nAssessing the factuality and relevance of domain-specific text produced by AI models\nCrafting and answering questions related to Machine Learning\nEvaluating and ranking domain-specific responses generated by AI models\n\nExamples of desirable expertise:\n\nA bachelor's or higher degree in Machine Learning or a related subject\nExperience working as an Machine Learning professional\nAbility to write clearly about concepts related to Machine Learning in fluent English\n\nPayment:\nCurrently, pay rates for core project work by Machine Learning experts range from $15 to $32 per hour USD.\n\nRates vary based on expertise, skills assessment, location, project need, and other factors. For example, higher rates may be offered to PhDs. For non-core work, such as during initial project onboarding or project overtime phases, lower rates may apply. Certain projects offer incentive payments. Please review the payment terms for each project.\n\nPLEASE NOTE: We collect, retain and use personal data for our professional business purposes, including notifying you of opportunities that may be of interest and sharing with our affiliates. We limit the personal data we collect to that which we believe is appropriate and necessary to manage applicants\u2019 needs, provide our services, and comply with applicable laws. Any information we collect in connection with your application will be treated in accordance with the Outlier Privacy Policy and our internal policies and programs designed to protect personal data.\nThis is a 1099 contract opportunity on the Outlier.ai platform. Because this is a freelance opportunity, we do not offer internships, sponsorship, or employment. You must be authorized to work in your country of residence. If you are an international student, you may be able to sign up for Outlier if you are on a visa. You should contact your tax and/or immigration advisor with specific questions regarding your circumstances."
"""

resume = """

Profile
    Data Analyst with experience in both large international companies and dynamic startups. Proficient in data-driven
    decision-making, building ETL pipelines, and creating insightful visualizations. 

Professional Experience:
    Data Analyst, ASQII - HealthTech · Internship [Aug 2024 - Sep 2024 · 2 months]
        •Currently working on a comprehensive data science project for the Tunisian National Health Insurance Fund.
        •Developing end-to-end data analysis solutions, providing actionable insights to improve national health policies

    Data Analyst, Sopra HR Software · Internship [Jun 2024 - Jul 2024 · 2 months]
        •Developed a robust ETL pipeline in Python to retrieve, preprocess, and clean data from an Oracle database.
        •Trained a machine learning model to predict employee churn, achieving 93% accuracy, and deployed it in a web
        application with a visualization dashboard.
        •Collaborated closely with international clients to deliver key statistics and insights, driving better decision-making.

Education
    Bachelor of Science in Business Administration (Graduation : 2025)
    Tunis Business School Major: Business Analytics Minor: International Business Economics
    Clubs:
        Google Developer Student Club - Tunis Business School
        Data Science Club TBS: ER member
    Relevant Courses: Data Analysis / Data Mining / Econometrics / Advanced Econometrics / Time Series Analysis

Projects
    A Dive into The Tunisian Car Market
        •Scraped and cleaned data on used cars from Tunisian marketplaces, standardizing formats and performing feature
        engineering.
        •Built and tuned machine learning models, achieving 92% accuracy in price prediction through model stacking.
        •Deployed results as a web app with interactive dashboards using Flask, Plotly, and other visualization tools.
    Data Salaries Dashboard
        •Performed data cleaning, feature engineering, and standardization (pandas).
        •Developed an interactive Power BI dashboard to provide insights into salaries across various job categories and
        countries

Organizations
2023/06 – 2023/07 AIESEC Turkey: Assistant English Teacher

Certificates
    Google Data Analytics Specialization
    August 2023
    Advanced Google Data Analytics Specialization
    Ongoing

Skills
Data Analysis (SQL, Python, R) , Machine Learning, Visualization (Power BI), ETL Pipelines, Web Development
(Flask), Blockchain/Web3, Collaboration & Communication.

Languages
English / Arabic / French
"""




content  = f"""you received this resume: {resume}. 

    analyse the job descrition and the candidates resume and give him a score on how he fits the job.
    this person is from tunisia and is residing there so if the job descrition doesnt allighn with that directly reject.
            
    your response should be in this forrmat:
   ( result : accept / reject (if score is below 7 reject)
    score : from 0 to 10
    rejection reason : one of the followong (skill issue / residence issue) note : only show this when rejected)
    acceptance reason : 

    and nothing else
    """

client = Groq(api_key = "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")

completion = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {
            "role": "system",
            "content": f"You are an experienced recruiter working for {company_name}, you posted a job online. here are the details of the job: {description}."
        },
        {
            "role": "user",
            "content": content
        }
    ],
    temperature=1,
    max_tokens=3240,
    top_p=1,
    stream=False,
    stop=None,
)

print(completion.choices[0].message.content)





